---

- name: Install Supervisord
  package:
    name="{{ supervisord_package }}"
    state="present"

- name: Configure Programs
  template:
    src="program.ini.j2"
    dest="{{ supervisord_conf_d }}/{{ item.name }}.ini"
  with_items: "{{ supervisord_programs }}
